"""
Script to create a mock medical report PDF for testing the Aivara system.
"""

import os
from datetime import datetime

# Try to use reportlab, fallback to creating a text file if not available
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import inch
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("reportlab not available, will create a text file instead")

def create_mock_report_pdf():
    """Create a mock medical report PDF with health markers"""
    
    output_path = os.path.join(os.path.dirname(__file__), "mock_medical_report.pdf")
    
    if REPORTLAB_AVAILABLE:
        # Create PDF using reportlab
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter
        
        # Title
        c.setFont("Helvetica-Bold", 16)
        c.drawString(100, height - 50, "MEDICAL LABORATORY REPORT")
        
        # Header information
        c.setFont("Helvetica", 12)
        y = height - 100
        c.drawString(100, y, "Patient Name: John Doe")
        y -= 20
        c.drawString(100, y, f"Date: {datetime.now().strftime('%Y-%m-%d')}")
        y -= 20
        c.drawString(100, y, "Lab ID: LAB-2024-001")
        y -= 20
        c.drawString(100, y, "Physician: Dr. Smith")
        
        # Section header
        y -= 40
        c.setFont("Helvetica-Bold", 14)
        c.drawString(100, y, "COMPLETE BLOOD COUNT (CBC)")
        y -= 30
        
        # Test results in a table format
        c.setFont("Helvetica", 11)
        results = [
            ("Test", "Result", "Unit", "Reference Range"),
            ("Hemoglobin (Hb)", "14.5", "g/dL", "12.0 - 17.5"),
            ("White Blood Cell Count (WBC)", "7.2", "x10³/µL", "4.0 - 11.0"),
            ("Platelets", "280", "x10³/µL", "150 - 450"),
            ("Red Blood Cell Count (RBC)", "5.0", "x10⁶/µL", "4.5 - 5.9"),
        ]
        
        x_positions = [100, 250, 350, 450]
        
        for row_idx, row in enumerate(results):
            if row_idx == 0:
                c.setFont("Helvetica-Bold", 10)
            else:
                c.setFont("Helvetica", 10)
            
            for col_idx, text in enumerate(row):
                c.drawString(x_positions[col_idx], y, text)
            y -= 20
        
        # Additional notes
        y -= 30
        c.setFont("Helvetica", 10)
        c.drawString(100, y, "Notes:")
        y -= 20
        c.drawString(100, y, "All values are within normal reference ranges.")
        y -= 20
        c.drawString(100, y, "No abnormalities detected in this report.")
        y -= 20
        c.drawString(100, y, "Recommend follow-up in 6 months for routine check.")
        
        # Footer
        y = 50
        c.setFont("Helvetica", 8)
        c.drawString(100, y, "This is a mock medical report for testing purposes.")
        c.drawString(100, y - 15, "Generated by Aivara Test System")
        
        c.save()
        print(f"Created mock PDF: {output_path}")
        return output_path
    else:
        # Fallback: Create a text file that can be used with pdfplumber
        # Users can convert it to PDF or use it directly if system supports .txt
        content = f"""
MEDICAL LABORATORY REPORT

Patient Name: John Doe
Date: {datetime.now().strftime('%Y-%m-%d')}
Lab ID: LAB-2024-001
Physician: Dr. Smith

COMPLETE BLOOD COUNT (CBC)

Test                        Result    Unit         Reference Range
Hemoglobin (Hb)             14.5      g/dL         12.0 - 17.5
White Blood Cell Count       7.2      x10^3/uL      4.0 - 11.0
Platelets                  280       x10^3/uL      150 - 450
Red Blood Cell Count (RBC)   5.0      x10^6/uL      4.5 - 5.9

Notes:
All values are within normal reference ranges.
No abnormalities detected in this report.
Recommend follow-up in 6 months for routine check.

Alternative formats:
Hb: 14.5 g/dL
HGB: 14.5
WBC: 7.2 x10^3/uL
White Blood Cell: 7.2
Platelets: 280
PLTS: 280
RBC: 5.0 x10^6/uL
Red Blood Cell: 5.0

---
This is a mock medical report for testing purposes.
Generated by Aivara Test System
"""
        output_path = os.path.join(os.path.dirname(__file__), "mock_medical_report.txt")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Created mock text file: {output_path}")
        print("Note: Install reportlab to create PDF: pip install reportlab")
        return output_path

if __name__ == "__main__":
    create_mock_report_pdf()

